site_name: Facile Docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/favicon.ico
  
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      # primary: blue
      toggle:
        icon: material/brightness-auto
        name: Mudar para modo escuro

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      # primary: blue
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Mudar para automático

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      # primary: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

nav:
  - Home: 'index.md'
  - Facile XML-e: 
    - Introdução: 'xmle/index.md'
    - Notas de Versão:
      - Notas: 'xmle/release-notes.md'
      - Prefeituras Homologadas: 'xmle/prefeituras.md'
    - Download do Patch: 'xmle/download-patch.md'
    - Dicionário de Dados: 'xmle/dicionario-dados.md'
    - Instalação:
      - Passo 01 - Aplicando o Patch: 'xmle/instalacao/aplicar-patch.md'
      - Passo 02 - Compatibilizador: 'xmle/instalacao/compatibilizador.md'
      - Passo 03 - Pontos de Entrada: 'xmle/instalacao/ponto-entrada-padrao.md'
      - Passo 04 - Criando os Menus: 'xmle/instalacao/menus.md'
      - Passo 05 - Configurar os Jobs: 'xmle/instalacao/configura-jobs.md'
    - Manuais:
      - 03 - Manual do Usuário: 'xmle/manuais/manual-usuario.md'
      - 04 - Importação de XML manual: 'xmle/manuais/importacao-manual.md'
      - 05 - Processo de fracionar itens: 'xmle/manuais/fracionar-itens.md'
      - 06 - Funcionalidades para o Pedido de Compra: 'xmle/manuais/pc-completo.md'
      - 07 - Filtro de XML sem nota de entrada: 'xmle/manuais/xml-sem-entrada.md'
      - 08 - Manifestação em lote: 'xmle/manuais/manifestacao-lote.md'
      - 09 - CheckDoc: 'xmle/manuais/checkdoc.md'
      - 10 - Devolução de Venda: 'xmle/manuais/devol-venda.md'
      - 12 - Atualização de Certificado digital: 'xmle/manuais/att-cd.md'
      - 13 - Entrada em Lote: 'xmle/manuais/entrada-lote.md'
      - 14 - Configuração do Webservice Checkdoc: 'xmle/manuais/webservice.md'
      - 15 - Gerar Pré-Nota de Entrada com o Checkdoc: 'xmle/manuais/prenota-checkdoc.md'
      - 16 - Importar XML por e-mail: 'xmle/manuais/xml-email.md'
      - 17 - Regras por Processo: 'xmle/manuais/regras-classi.md'
      - 18 - Segunda Unidade de Medida da Amarração Produto x Fornecedor: 'xmle/manuais/produtoxforn.md'
      - 19 - Lista de Pontos de Entrada: 'xmle/manuais/peferramenta.md'
      - 20 - Cancelar Conhecimento de Frete: 'xmle/manuais/cancelar-cte.md'
    - Anexos:
      - 01 - Modelo de e-mail para fornecedores: 'xmle/anexos/email-fornecedores.md'
      - Videos:
        - 01 - Apresentação Ferramenta FACILE XML-e: 'https://www.youtube.com/watch?v=cJyqAefUalU&t=16s'
        - 02 - Importação de XML no ERP Protheus. Conheço o novo FACILE XML-e: 'https://www.youtube.com/watch?v=LcOI3j66tRc'
        - 03 - Manual Central FACILE XML-e - 01 Ajustes e inclusão Vários Itens em Um: 'https://www.youtube.com/watch?v=TTBkagNY2KI'
        - 04 - Importador XML no Totvs Protheus - Como funciona e Qual usar?: 'https://www.youtube.com/watch?v=mG0ZtHArLYo'
  - CIFA:
    - Introdução: 'cifa/index.md'
    - Download do Patch: 'cifa/download-patch.md'
  - Facin Sales: https://www.facilesistemas.com.br/facin/

plugins:
  - search
  
copyright: Copyright &copy; 2010 - 2023 Facile Sistemas

extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/facilesistemass
      name: Facile no Facebook

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/facilesistemas/
      name: Siga nosso instagram
    
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/facile-solu-es-em-sistemas/
      name: LinkedIN

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list