site_name: Facile Docs

nav:
  - Home: 'index.md'

plugins:
  - search

copyright: Copyright &copy; 2010 - 2022 Facile Sistemas

extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/facilesistemass
      name: Facile no Facebook

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/facilesistemas/
      name: Siga nosso instagram
    
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/facile-solu-es-em-sistemas/
      name: LinkedIN

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/favicon.ico
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

